[package]
name = "kcl-lib-c"
version = "0.10.8"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]
doc = false

[build-dependencies]
cbindgen = "0.26.0"

[dependencies]
kclvm-api = { git = "https://github.com/kcl-lang/kcl", rev = "2aa8fea", version = "0.10.8" }
