[package]
name = "kcl-lib-dotnet"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
kclvm-api = { git = "https://github.com/kcl-lang/kcl", version = "0.10.0" }
