name: go-test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - "go/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-test.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-12, macos-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: "go"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Go code test
        run: go test ./...
