name: swift-test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - "swift/**"
      - ".github/workflows/swift-test.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    defaults:
      run:
        working-directory: "swift"
    strategy:
      matrix:
        os: [macos-13, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      if: "contains(matrix.os, 'ubuntu-latest')"
      run: |
        sudo apt-get update
        sudo apt-get install libgtest-dev ninja-build
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.81
        override: true
        components: clippy, rustfmt
    - name: Setup Swift toolchain
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: 5
    - name: Build and run tests
      run: make test
